/**
 * Token data for the docs pages. Generated by ../docs-site/scripts/generate-tokens.mjs
 * (run by `npm run tokens` before every dev and build), so Storybook and the docs site
 * read the same resolved values, alias chains, contrast ratios and platform names.
 */
import raw from "../../../docs-site/data/tokens.json";
import type { FlatToken, Platform, TokenData } from "../../../docs-site/lib/types";

export type { FlatToken, Platform };

export const data = raw as unknown as TokenData;

export type TokenSet = FlatToken["set"];

/** Tokens in one set whose path starts with `prefix` (a group such as `space` or `color.text-`). */
export const select = (set: TokenSet, prefix: string): FlatToken[] =>
  data.all.filter((token) => token.set === set && token.path.startsWith(prefix));

/** Top-level groups of a set, in source order: `color`, `space`, `button` … */
export const groupsOf = (set: TokenSet): string[] => [
  ...new Set(data.all.filter((token) => token.set === set).map((token) => token.path.split(".")[0])),
];

export const cssVar = (token: { names: { css: string } }) => `var(${token.names.css})`;

/** `{color.azure.700}` → `brand.700`, the way the README writes an alias. */
export const aliasLabel = (reference: string | null) =>
  reference ? reference.replace(/^color\./, "") : null;

/** One-line rendering of a token value; shadows become their CSS shorthand. */
export function formatValue(token: FlatToken): string {
  const { value } = token;
  if (typeof value === "string") return value;
  if (Array.isArray(value)) {
    return value.map((layer) => `${layer.x} ${layer.y} ${layer.blur} ${layer.color}`).join(", ");
  }
  return Object.values(value).join(" / ");
}
