/**
 * Token data for the docs pages. Generated by ../docs-site/scripts/generate-tokens.mjs
 * (run by `npm run tokens` before every dev and build), so Storybook and the docs site
 * read the same resolved values, alias chains, contrast ratios and platform names.
 */
import { useSyncExternalStore } from "react";
import raw from "../../../docs-site/data/tokens.json";
import type { BrandData, FlatToken, Platform, TokenData } from "../../../docs-site/lib/types";

export type { BrandData, FlatToken, Platform };

export const data = raw as unknown as TokenData;

export type TokenSet = FlatToken["set"];

/** The brand the Brand toolbar has set on the root, so blocks re-render when it changes.
 * CSS variables follow data-brand on their own; this is for the values the blocks print. */
const subscribe = (onChange: () => void) => {
  const observer = new MutationObserver(onChange);
  observer.observe(document.documentElement, { attributes: true, attributeFilter: ["data-brand"] });
  return () => observer.disconnect();
};
const brandId = () => document.documentElement.dataset.brand ?? data.brands[0].id;

export function useBrand(): BrandData {
  const id = useSyncExternalStore(subscribe, brandId);
  return data.brands.find((brand) => brand.id === id) ?? data.brands[0];
}

/** A token with the value and alias it has in `brand`. */
export const inBrand = (token: FlatToken, brand: BrandData): FlatToken => {
  const override = brand.tokens[`${token.set}:${token.path}`];
  return override ? { ...token, ...override } : token;
};

/** Tokens in one set whose path starts with `prefix` (a group such as `space` or `color.text-`). */
export const select = (set: TokenSet, prefix: string): FlatToken[] =>
  data.all.filter((token) => token.set === set && token.path.startsWith(prefix));

/** Top-level groups of a set, in source order: `color`, `space`, `button` … */
export const groupsOf = (set: TokenSet): string[] => [
  ...new Set(data.all.filter((token) => token.set === set).map((token) => token.path.split(".")[0])),
];

export const cssVar = (token: { names: { css: string } }) => `var(${token.names.css})`;

/** `{color.azure.700}` → `brand.700`, the way the README writes an alias. */
export const aliasLabel = (reference: string | null) =>
  reference ? reference.replace(/^color\./, "") : null;

/** One-line rendering of a token value; shadows become their CSS shorthand. */
export function formatValue(token: FlatToken): string {
  const { value } = token;
  if (typeof value === "string") return value;
  if (Array.isArray(value)) {
    // A curve is four control points; a shadow is a list of layers.
    if (value.every((n) => typeof n === "number")) return `cubic-bezier(${value.join(", ")})`;
    return (value as Record<string, unknown>[]).map((layer) => `${layer.x} ${layer.y} ${layer.blur} ${layer.color}`).join(", ");
  }
  if (token.type === "spring") return `${value.duration}, bounce ${value.bounce}`;
  return Object.values(value).join(" / ");
}
