// url=https://www.figma.com/design/byPBTSedTYOO0AYwmIlncH/Cosmos?node-id=635-123
// source=storybook/src/components/Icon/Icon.tsx
// component=Icon
// Generated by storybook/scripts/generate-icon-code-connect.mjs. Do not edit by hand.
import figma from "figma";

export default {
  example: figma.tsx`<Icon name="check-circle" />`,
  imports: ['import { Icon } from "@mmt/cosmos"'],
  id: "icon-check-circle",
  metadata: { nestable: true, props: { name: "check-circle" } },
};
