// url=https://www.figma.com/design/byPBTSedTYOO0AYwmIlncH/Cosmos?node-id=780-34
// source=https://github.com/ivineel11/mmt-cosmos-design-tokens/blob/main/storybook/src/components/Icon/Icon.tsx
// component=Icon
// Generated by storybook/scripts/generate-icon-code-connect.mjs. Do not edit by hand.
import figma from "figma";

export default {
  example: figma.tsx`<Icon name="delete" />`,
  imports: ['import { Icon } from "@mmt/cosmos"'],
  id: "icon-delete",
  metadata: { nestable: true, props: { name: "delete" } },
};
