// url=https://www.figma.com/design/byPBTSedTYOO0AYwmIlncH/Cosmos?node-id=55-11
// source=storybook/src/components/Icon/Icon.tsx
// component=Icon
// Generated by storybook/scripts/generate-icon-code-connect.mjs. Do not edit by hand.
import figma from "figma";

export default {
  example: figma.tsx`<Icon name="plus" />`,
  imports: ['import { Icon } from "@mmt/cosmos"'],
  id: "icon-plus",
  metadata: { nestable: true, props: { name: "plus" } },
};
